# Generated by Django 2.0.1 on 2019-02-05 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_imgupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=None, on_delete=False, related_name='articles', to='blog.ArticleCategory'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='author',
            field=models.ForeignKey(default=None, on_delete=False, related_name='article_ctg', to=settings.AUTH_USER_MODEL),
        ),
    ]
