# Generated by Django 2.0.1 on 2019-02-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190205_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
    ]
